#!/usr/bin/env bash

# Check if library has already been built.
if [ -f "lib/" ]; then
  echo "lib/ folder already exists; nothing to build."
  exit
fi
mkdir -p lib/

# Check if everything is installed
res=0
gradle --version >> /dev/null
if [ $? -ne 0 ]; then
  echo "Gradle not installed; refer to https://gradle.org/install for installation instructions." >&2
  res=1
fi

mvn --version >> /dev/null
if [ $? -ne 0 ]; then
  echo "Maven not installed; refer to http://maven.apache.org/install.html for installation instructions." >&2
  res=1
fi

if [[ -f "/usr/share/javacc.jar" ]] || [[ -f "/usr/share/JavaCC.zip" ]] || [[ -f "${JAVACC_HOME}/javacc.jar" ]] || [[ -f "${JAVACC_HOME} /JavaCC.zip" ]]
then
  :
else 
  echo "JavaCC cannot be found; refer to https://github.com/javacc/javacc#download for installation instructions."
  res=1
fi

if [ $res -ne 0 ]; then 
  echo "Some tools not installed;  try again after installing them."
  exit
else 
  echo "Found all necessary tools, start the building process."
fi 

cd lib_sources

cd automatalib
echo "Building automatalib with maven."
mvn clean package -Pbundles -Dmaven.javadoc.skip=true >> /dev/null
cd .. # back to lib_sources

cd owl
echo "Building owl with gradle."
./gradlew minimizedDistZip >> /dev/null
cd .. # back to lib_sources

cd rltl2ltl
echo "Building rltl2ltl with ant."
ant jar  >> /dev/null
cd .. # back to lib_sources

cd .. # back to root

# Move jars to lib/.
echo "Moving generated jar files to lib/ folder."
mv lib_sources/owl/build/distributions/owl-minimized-20.XX-development.zip lib/owl.zip
cd lib 
unzip owl.zip
mv owl-minimized-20.XX-development/lib/owl-20.XX-development-all.jar owl.jar
cd ..

for i in lib_sources/automatalib/distribution/target/bundles/*.jar; do
    [ -f "$i" ] || break
    mv "$i" lib/
done
mv lib_sources/rltl2ltl/rltl2ltl.jar lib/




# git clone https://gitlab.lrz.de/i7/owl.git
# remove line 292 in owl/build.gradle
# require jdk 12, download from https://jdk.java.net/13/  move to proper location. On mac use brew cask install java, when permission error, navigate to system preferences, security & privacy, in general tab, allow for running openjdk